
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const ActivityGrid: typeof import("../components/activity/Grid.vue")['default']
export const CommonAppToast: typeof import("../components/common/AppToast.vue")['default']
export const CommonBaseDatePicker: typeof import("../components/common/BaseDatePicker.vue")['default']
export const CommonCard: typeof import("../components/common/Card.vue")['default']
export const CommonDataGrid: typeof import("../components/common/DataGrid.vue")['default']
export const CommonDateRange: typeof import("../components/common/DateRange.vue")['default']
export const CommonGrid: typeof import("../components/common/Grid.vue")['default']
export const CommonLoader: typeof import("../components/common/Loader.vue")['default']
export const CommonNumber: typeof import("../components/common/Number.vue")['default']
export const CommonPagedGrid: typeof import("../components/common/PagedGrid.vue")['default']
export const VerificationsContent: typeof import("../components/verifications/Content.vue")['default']
export const VerificationsDocsModal: typeof import("../components/verifications/DocsModal.vue")['default']
export const VerificationsGrid: typeof import("../components/verifications/Grid.vue")['default']
export const VerificationsVerifyModal: typeof import("../components/verifications/VerifyModal.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const BAccordion: typeof import("bootstrap-vue-next/components/BAccordion")['BAccordion']
export const BAccordionItem: typeof import("bootstrap-vue-next/components/BAccordion")['BAccordionItem']
export const BAlert: typeof import("bootstrap-vue-next/components/BAlert")['BAlert']
export const BApp: typeof import("bootstrap-vue-next/components/BApp")['BApp']
export const BAvatar: typeof import("bootstrap-vue-next/components/BAvatar")['BAvatar']
export const BAvatarGroup: typeof import("bootstrap-vue-next/components/BAvatar")['BAvatarGroup']
export const BBadge: typeof import("bootstrap-vue-next/components/BBadge")['BBadge']
export const BBreadcrumb: typeof import("bootstrap-vue-next/components/BBreadcrumb")['BBreadcrumb']
export const BBreadcrumbItem: typeof import("bootstrap-vue-next/components/BBreadcrumb")['BBreadcrumbItem']
export const BButton: typeof import("bootstrap-vue-next/components/BButton")['BButton']
export const BButtonGroup: typeof import("bootstrap-vue-next/components/BButton")['BButtonGroup']
export const BButtonToolbar: typeof import("bootstrap-vue-next/components/BButton")['BButtonToolbar']
export const BCloseButton: typeof import("bootstrap-vue-next/components/BButton")['BCloseButton']
export const BCard: typeof import("bootstrap-vue-next/components/BCard")['BCard']
export const BCardBody: typeof import("bootstrap-vue-next/components/BCard")['BCardBody']
export const BCardFooter: typeof import("bootstrap-vue-next/components/BCard")['BCardFooter']
export const BCardGroup: typeof import("bootstrap-vue-next/components/BCard")['BCardGroup']
export const BCardHeader: typeof import("bootstrap-vue-next/components/BCard")['BCardHeader']
export const BCardImg: typeof import("bootstrap-vue-next/components/BCard")['BCardImg']
export const BCardSubtitle: typeof import("bootstrap-vue-next/components/BCard")['BCardSubtitle']
export const BCardText: typeof import("bootstrap-vue-next/components/BCard")['BCardText']
export const BCardTitle: typeof import("bootstrap-vue-next/components/BCard")['BCardTitle']
export const BCarousel: typeof import("bootstrap-vue-next/components/BCarousel")['BCarousel']
export const BCarouselSlide: typeof import("bootstrap-vue-next/components/BCarousel")['BCarouselSlide']
export const BCol: typeof import("bootstrap-vue-next/components/BContainer")['BCol']
export const BCollapse: typeof import("bootstrap-vue-next/components/BCollapse")['BCollapse']
export const BContainer: typeof import("bootstrap-vue-next/components/BContainer")['BContainer']
export const BDropdown: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdown']
export const BDropdownDivider: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownDivider']
export const BDropdownForm: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownForm']
export const BDropdownGroup: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownGroup']
export const BDropdownHeader: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownHeader']
export const BDropdownItem: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownItem']
export const BDropdownItemButton: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownItemButton']
export const BDropdownText: typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownText']
export const BForm: typeof import("bootstrap-vue-next/components/BForm")['BForm']
export const BFormCheckbox: typeof import("bootstrap-vue-next/components/BFormCheckbox")['BFormCheckbox']
export const BFormCheckboxGroup: typeof import("bootstrap-vue-next/components/BFormCheckbox")['BFormCheckboxGroup']
export const BFormDatalist: typeof import("bootstrap-vue-next/components/BForm")['BFormDatalist']
export const BFormFile: typeof import("bootstrap-vue-next/components/BFormFile")['BFormFile']
export const BFormFloatingLabel: typeof import("bootstrap-vue-next/components/BForm")['BFormFloatingLabel']
export const BFormGroup: typeof import("bootstrap-vue-next/components/BFormGroup")['BFormGroup']
export const BFormInput: typeof import("bootstrap-vue-next/components/BFormInput")['BFormInput']
export const BFormInvalidFeedback: typeof import("bootstrap-vue-next/components/BForm")['BFormInvalidFeedback']
export const BFormRadio: typeof import("bootstrap-vue-next/components/BFormRadio")['BFormRadio']
export const BFormRadioGroup: typeof import("bootstrap-vue-next/components/BFormRadio")['BFormRadioGroup']
export const BFormRating: typeof import("bootstrap-vue-next/components/BFormRating")['BFormRating']
export const BFormRow: typeof import("bootstrap-vue-next/components/BForm")['BFormRow']
export const BFormSelect: typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelect']
export const BFormSelectOption: typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelectOption']
export const BFormSelectOptionGroup: typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelectOptionGroup']
export const BFormSpinbutton: typeof import("bootstrap-vue-next/components/BFormSpinbutton")['BFormSpinbutton']
export const BFormTag: typeof import("bootstrap-vue-next/components/BFormTags")['BFormTag']
export const BFormTags: typeof import("bootstrap-vue-next/components/BFormTags")['BFormTags']
export const BFormText: typeof import("bootstrap-vue-next/components/BForm")['BFormText']
export const BFormTextarea: typeof import("bootstrap-vue-next/components/BFormTextarea")['BFormTextarea']
export const BFormValidFeedback: typeof import("bootstrap-vue-next/components/BForm")['BFormValidFeedback']
export const BImg: typeof import("bootstrap-vue-next/components/BImg")['BImg']
export const BInput: typeof import("bootstrap-vue-next/components/BFormInput")['BInput']
export const BInputGroup: typeof import("bootstrap-vue-next/components/BInputGroup")['BInputGroup']
export const BInputGroupText: typeof import("bootstrap-vue-next/components/BInputGroup")['BInputGroupText']
export const BListGroup: typeof import("bootstrap-vue-next/components/BListGroup")['BListGroup']
export const BListGroupItem: typeof import("bootstrap-vue-next/components/BListGroup")['BListGroupItem']
export const BModal: typeof import("bootstrap-vue-next/components/BModal")['BModal']
export const BModalOrchestrator: typeof import("bootstrap-vue-next/components/BModal")['BModalOrchestrator']
export const BNav: typeof import("bootstrap-vue-next/components/BNav")['BNav']
export const BNavForm: typeof import("bootstrap-vue-next/components/BNav")['BNavForm']
export const BNavItem: typeof import("bootstrap-vue-next/components/BNav")['BNavItem']
export const BNavItemDropdown: typeof import("bootstrap-vue-next/components/BNav")['BNavItemDropdown']
export const BNavText: typeof import("bootstrap-vue-next/components/BNav")['BNavText']
export const BNavbar: typeof import("bootstrap-vue-next/components/BNavbar")['BNavbar']
export const BNavbarBrand: typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarBrand']
export const BNavbarNav: typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarNav']
export const BNavbarToggle: typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarToggle']
export const BOffcanvas: typeof import("bootstrap-vue-next/components/BOffcanvas")['BOffcanvas']
export const BOverlay: typeof import("bootstrap-vue-next/components/BOverlay")['BOverlay']
export const BOrchestrator: typeof import("bootstrap-vue-next/components/BApp")['BOrchestrator']
export const BPagination: typeof import("bootstrap-vue-next/components/BPagination")['BPagination']
export const BPlaceholder: typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholder']
export const BPlaceholderButton: typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderButton']
export const BPlaceholderCard: typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderCard']
export const BPlaceholderTable: typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderTable']
export const BPlaceholderWrapper: typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderWrapper']
export const BPopover: typeof import("bootstrap-vue-next/components/BPopover")['BPopover']
export const BProgress: typeof import("bootstrap-vue-next/components/BProgress")['BProgress']
export const BRow: typeof import("bootstrap-vue-next/components/BContainer")['BRow']
export const BSpinner: typeof import("bootstrap-vue-next/components/BSpinner")['BSpinner']
export const BTab: typeof import("bootstrap-vue-next/components/BTabs")['BTab']
export const BTabs: typeof import("bootstrap-vue-next/components/BTabs")['BTabs']
export const BToast: typeof import("bootstrap-vue-next/components/BToast")['BToast']
export const BToastOrchestrator: typeof import("bootstrap-vue-next/components/BToast")['BToastOrchestrator']
export const BTooltip: typeof import("bootstrap-vue-next/components/BTooltip")['BTooltip']
export const BLink: typeof import("bootstrap-vue-next/components/BLink")['BLink']
export const BProgressBar: typeof import("bootstrap-vue-next/components/BProgress")['BProgressBar']
export const BTableSimple: typeof import("bootstrap-vue-next/components/BTable")['BTableSimple']
export const BTableLite: typeof import("bootstrap-vue-next/components/BTable")['BTableLite']
export const BTable: typeof import("bootstrap-vue-next/components/BTable")['BTable']
export const BTbody: typeof import("bootstrap-vue-next/components/BTable")['BTbody']
export const BTd: typeof import("bootstrap-vue-next/components/BTable")['BTd']
export const BTh: typeof import("bootstrap-vue-next/components/BTable")['BTh']
export const BThead: typeof import("bootstrap-vue-next/components/BTable")['BThead']
export const BTfoot: typeof import("bootstrap-vue-next/components/BTable")['BTfoot']
export const BTr: typeof import("bootstrap-vue-next/components/BTable")['BTr']
export const BPopoverOrchestrator: typeof import("bootstrap-vue-next/components/BPopover")['BPopoverOrchestrator']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyActivityGrid: LazyComponent<typeof import("../components/activity/Grid.vue")['default']>
export const LazyCommonAppToast: LazyComponent<typeof import("../components/common/AppToast.vue")['default']>
export const LazyCommonBaseDatePicker: LazyComponent<typeof import("../components/common/BaseDatePicker.vue")['default']>
export const LazyCommonCard: LazyComponent<typeof import("../components/common/Card.vue")['default']>
export const LazyCommonDataGrid: LazyComponent<typeof import("../components/common/DataGrid.vue")['default']>
export const LazyCommonDateRange: LazyComponent<typeof import("../components/common/DateRange.vue")['default']>
export const LazyCommonGrid: LazyComponent<typeof import("../components/common/Grid.vue")['default']>
export const LazyCommonLoader: LazyComponent<typeof import("../components/common/Loader.vue")['default']>
export const LazyCommonNumber: LazyComponent<typeof import("../components/common/Number.vue")['default']>
export const LazyCommonPagedGrid: LazyComponent<typeof import("../components/common/PagedGrid.vue")['default']>
export const LazyVerificationsContent: LazyComponent<typeof import("../components/verifications/Content.vue")['default']>
export const LazyVerificationsDocsModal: LazyComponent<typeof import("../components/verifications/DocsModal.vue")['default']>
export const LazyVerificationsGrid: LazyComponent<typeof import("../components/verifications/Grid.vue")['default']>
export const LazyVerificationsVerifyModal: LazyComponent<typeof import("../components/verifications/VerifyModal.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyBAccordion: LazyComponent<typeof import("bootstrap-vue-next/components/BAccordion")['BAccordion']>
export const LazyBAccordionItem: LazyComponent<typeof import("bootstrap-vue-next/components/BAccordion")['BAccordionItem']>
export const LazyBAlert: LazyComponent<typeof import("bootstrap-vue-next/components/BAlert")['BAlert']>
export const LazyBApp: LazyComponent<typeof import("bootstrap-vue-next/components/BApp")['BApp']>
export const LazyBAvatar: LazyComponent<typeof import("bootstrap-vue-next/components/BAvatar")['BAvatar']>
export const LazyBAvatarGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BAvatar")['BAvatarGroup']>
export const LazyBBadge: LazyComponent<typeof import("bootstrap-vue-next/components/BBadge")['BBadge']>
export const LazyBBreadcrumb: LazyComponent<typeof import("bootstrap-vue-next/components/BBreadcrumb")['BBreadcrumb']>
export const LazyBBreadcrumbItem: LazyComponent<typeof import("bootstrap-vue-next/components/BBreadcrumb")['BBreadcrumbItem']>
export const LazyBButton: LazyComponent<typeof import("bootstrap-vue-next/components/BButton")['BButton']>
export const LazyBButtonGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BButton")['BButtonGroup']>
export const LazyBButtonToolbar: LazyComponent<typeof import("bootstrap-vue-next/components/BButton")['BButtonToolbar']>
export const LazyBCloseButton: LazyComponent<typeof import("bootstrap-vue-next/components/BButton")['BCloseButton']>
export const LazyBCard: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCard']>
export const LazyBCardBody: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardBody']>
export const LazyBCardFooter: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardFooter']>
export const LazyBCardGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardGroup']>
export const LazyBCardHeader: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardHeader']>
export const LazyBCardImg: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardImg']>
export const LazyBCardSubtitle: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardSubtitle']>
export const LazyBCardText: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardText']>
export const LazyBCardTitle: LazyComponent<typeof import("bootstrap-vue-next/components/BCard")['BCardTitle']>
export const LazyBCarousel: LazyComponent<typeof import("bootstrap-vue-next/components/BCarousel")['BCarousel']>
export const LazyBCarouselSlide: LazyComponent<typeof import("bootstrap-vue-next/components/BCarousel")['BCarouselSlide']>
export const LazyBCol: LazyComponent<typeof import("bootstrap-vue-next/components/BContainer")['BCol']>
export const LazyBCollapse: LazyComponent<typeof import("bootstrap-vue-next/components/BCollapse")['BCollapse']>
export const LazyBContainer: LazyComponent<typeof import("bootstrap-vue-next/components/BContainer")['BContainer']>
export const LazyBDropdown: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdown']>
export const LazyBDropdownDivider: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownDivider']>
export const LazyBDropdownForm: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownForm']>
export const LazyBDropdownGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownGroup']>
export const LazyBDropdownHeader: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownHeader']>
export const LazyBDropdownItem: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownItem']>
export const LazyBDropdownItemButton: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownItemButton']>
export const LazyBDropdownText: LazyComponent<typeof import("bootstrap-vue-next/components/BDropdown")['BDropdownText']>
export const LazyBForm: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BForm']>
export const LazyBFormCheckbox: LazyComponent<typeof import("bootstrap-vue-next/components/BFormCheckbox")['BFormCheckbox']>
export const LazyBFormCheckboxGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormCheckbox")['BFormCheckboxGroup']>
export const LazyBFormDatalist: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormDatalist']>
export const LazyBFormFile: LazyComponent<typeof import("bootstrap-vue-next/components/BFormFile")['BFormFile']>
export const LazyBFormFloatingLabel: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormFloatingLabel']>
export const LazyBFormGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormGroup")['BFormGroup']>
export const LazyBFormInput: LazyComponent<typeof import("bootstrap-vue-next/components/BFormInput")['BFormInput']>
export const LazyBFormInvalidFeedback: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormInvalidFeedback']>
export const LazyBFormRadio: LazyComponent<typeof import("bootstrap-vue-next/components/BFormRadio")['BFormRadio']>
export const LazyBFormRadioGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormRadio")['BFormRadioGroup']>
export const LazyBFormRating: LazyComponent<typeof import("bootstrap-vue-next/components/BFormRating")['BFormRating']>
export const LazyBFormRow: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormRow']>
export const LazyBFormSelect: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelect']>
export const LazyBFormSelectOption: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelectOption']>
export const LazyBFormSelectOptionGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSelect")['BFormSelectOptionGroup']>
export const LazyBFormSpinbutton: LazyComponent<typeof import("bootstrap-vue-next/components/BFormSpinbutton")['BFormSpinbutton']>
export const LazyBFormTag: LazyComponent<typeof import("bootstrap-vue-next/components/BFormTags")['BFormTag']>
export const LazyBFormTags: LazyComponent<typeof import("bootstrap-vue-next/components/BFormTags")['BFormTags']>
export const LazyBFormText: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormText']>
export const LazyBFormTextarea: LazyComponent<typeof import("bootstrap-vue-next/components/BFormTextarea")['BFormTextarea']>
export const LazyBFormValidFeedback: LazyComponent<typeof import("bootstrap-vue-next/components/BForm")['BFormValidFeedback']>
export const LazyBImg: LazyComponent<typeof import("bootstrap-vue-next/components/BImg")['BImg']>
export const LazyBInput: LazyComponent<typeof import("bootstrap-vue-next/components/BFormInput")['BInput']>
export const LazyBInputGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BInputGroup")['BInputGroup']>
export const LazyBInputGroupText: LazyComponent<typeof import("bootstrap-vue-next/components/BInputGroup")['BInputGroupText']>
export const LazyBListGroup: LazyComponent<typeof import("bootstrap-vue-next/components/BListGroup")['BListGroup']>
export const LazyBListGroupItem: LazyComponent<typeof import("bootstrap-vue-next/components/BListGroup")['BListGroupItem']>
export const LazyBModal: LazyComponent<typeof import("bootstrap-vue-next/components/BModal")['BModal']>
export const LazyBModalOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BModal")['BModalOrchestrator']>
export const LazyBNav: LazyComponent<typeof import("bootstrap-vue-next/components/BNav")['BNav']>
export const LazyBNavForm: LazyComponent<typeof import("bootstrap-vue-next/components/BNav")['BNavForm']>
export const LazyBNavItem: LazyComponent<typeof import("bootstrap-vue-next/components/BNav")['BNavItem']>
export const LazyBNavItemDropdown: LazyComponent<typeof import("bootstrap-vue-next/components/BNav")['BNavItemDropdown']>
export const LazyBNavText: LazyComponent<typeof import("bootstrap-vue-next/components/BNav")['BNavText']>
export const LazyBNavbar: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar")['BNavbar']>
export const LazyBNavbarBrand: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarBrand']>
export const LazyBNavbarNav: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarNav']>
export const LazyBNavbarToggle: LazyComponent<typeof import("bootstrap-vue-next/components/BNavbar")['BNavbarToggle']>
export const LazyBOffcanvas: LazyComponent<typeof import("bootstrap-vue-next/components/BOffcanvas")['BOffcanvas']>
export const LazyBOverlay: LazyComponent<typeof import("bootstrap-vue-next/components/BOverlay")['BOverlay']>
export const LazyBOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BApp")['BOrchestrator']>
export const LazyBPagination: LazyComponent<typeof import("bootstrap-vue-next/components/BPagination")['BPagination']>
export const LazyBPlaceholder: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholder']>
export const LazyBPlaceholderButton: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderButton']>
export const LazyBPlaceholderCard: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderCard']>
export const LazyBPlaceholderTable: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderTable']>
export const LazyBPlaceholderWrapper: LazyComponent<typeof import("bootstrap-vue-next/components/BPlaceholder")['BPlaceholderWrapper']>
export const LazyBPopover: LazyComponent<typeof import("bootstrap-vue-next/components/BPopover")['BPopover']>
export const LazyBProgress: LazyComponent<typeof import("bootstrap-vue-next/components/BProgress")['BProgress']>
export const LazyBRow: LazyComponent<typeof import("bootstrap-vue-next/components/BContainer")['BRow']>
export const LazyBSpinner: LazyComponent<typeof import("bootstrap-vue-next/components/BSpinner")['BSpinner']>
export const LazyBTab: LazyComponent<typeof import("bootstrap-vue-next/components/BTabs")['BTab']>
export const LazyBTabs: LazyComponent<typeof import("bootstrap-vue-next/components/BTabs")['BTabs']>
export const LazyBToast: LazyComponent<typeof import("bootstrap-vue-next/components/BToast")['BToast']>
export const LazyBToastOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BToast")['BToastOrchestrator']>
export const LazyBTooltip: LazyComponent<typeof import("bootstrap-vue-next/components/BTooltip")['BTooltip']>
export const LazyBLink: LazyComponent<typeof import("bootstrap-vue-next/components/BLink")['BLink']>
export const LazyBProgressBar: LazyComponent<typeof import("bootstrap-vue-next/components/BProgress")['BProgressBar']>
export const LazyBTableSimple: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTableSimple']>
export const LazyBTableLite: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTableLite']>
export const LazyBTable: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTable']>
export const LazyBTbody: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTbody']>
export const LazyBTd: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTd']>
export const LazyBTh: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTh']>
export const LazyBThead: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BThead']>
export const LazyBTfoot: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTfoot']>
export const LazyBTr: LazyComponent<typeof import("bootstrap-vue-next/components/BTable")['BTr']>
export const LazyBPopoverOrchestrator: LazyComponent<typeof import("bootstrap-vue-next/components/BPopover")['BPopoverOrchestrator']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
